"""Add invite_codes

Revision ID: 3c467be8dd82
Revises: 2b0cec39e646
Create Date: 2025-11-21 11:27:04.965112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c467be8dd82'
down_revision: Union[str, Sequence[str], None] = '2b0cec39e646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('registration_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_codes_code'), 'invite_codes', ['code'], unique=False)
    op.create_index(op.f('ix_invite_codes_user_id'), 'invite_codes', ['user_id'], unique=False)
    op.alter_column('user_identities', 'provider',
               existing_type=postgresql.ENUM('google', 'password', 'telegram', name='identityprovider'),
               type_=sa.Enum('GOOGLE', 'PASSWORD', 'TELEGRAM', name='identityprovider', native_enum=False, length=20),
               existing_nullable=False)
    op.add_column('users', sa.Column('ref_code', sa.String(length=8), nullable=False))
    op.add_column('users', sa.Column('refferer_code', sa.String(length=8), nullable=True))
    op.alter_column('users', 'plan_type',
               existing_type=postgresql.ENUM('free', 'pro', 'partner', name='plantype'),
               type_=sa.Enum('FREE', 'PRO', 'PARTNER', name='plantype', native_enum=False, length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_users_ref_code'), 'users', ['ref_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_ref_code'), table_name='users')
    op.alter_column('users', 'plan_type',
               existing_type=sa.Enum('FREE', 'PRO', 'PARTNER', name='plantype', native_enum=False, length=20),
               type_=postgresql.ENUM('free', 'pro', 'partner', name='plantype'),
               existing_nullable=False)
    op.drop_column('users', 'refferer_code')
    op.drop_column('users', 'ref_code')
    op.alter_column('user_identities', 'provider',
               existing_type=sa.Enum('GOOGLE', 'PASSWORD', 'TELEGRAM', name='identityprovider', native_enum=False, length=20),
               type_=postgresql.ENUM('google', 'password', 'telegram', name='identityprovider'),
               existing_nullable=False)
    op.drop_index(op.f('ix_invite_codes_user_id'), table_name='invite_codes')
    op.drop_index(op.f('ix_invite_codes_code'), table_name='invite_codes')
    op.drop_table('invite_codes')
    # ### end Alembic commands ###
