---
# tasks file for migrations
- name: Создать базовую директорию для проектов
  file:
    path: "{{ project_base }}"
    state: directory
    mode: "0755"
  become: yes
  become_user: "{{ lookup('env', 'AIDA_USER') }}"


- name: Установить Python, pip, venv
  apt:
    name:
      - python3
      - python3-venv
      - python3-pip
    state: present
    update_cache: yes
  become: yes
  become_user: root

- name: Копировать проект на сервер
  synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    recursive: yes
    delete: yes
  loop: "{{ projects }}"
  loop_control:
      label: "{{ item.name }}"
  become: yes
  become_user: "{{ lookup('env', 'AIDA_USER') }}"


- name: Создать виртуальное окружение
  command: "~/.pyenv/shims/python3 -m venv {{ item.venv }}"
  args:
    creates: "{{ item.venv }}/bin/activate"
  loop: "{{ projects }}"
  loop_control:
    label: "{{ item.name }}"
  become: yes
  become_user: "{{ lookup('env', 'AIDA_USER') }}"

- name: Установить зависимости проекта
  command: "{{ item.venv }}/bin/pip install -r requirements.txt"
  args:
    chdir: "{{ item.dest }}"
  loop: "{{ projects }}"
  loop_control:
    label: "{{ item.name }}"
  become: yes
  become_user: "{{ lookup('env', 'AIDA_USER') }}"



- name: Применить миграции Alembic
  command: "{{ item.venv }}/bin/alembic -c {{ item.alembic_config }} upgrade head"
  args:
    chdir: "{{ item.dest }}"
  environment:
    DATABASE_URL: "postgresql://{{ db_user }}:{{ db_password }}@{{ db_host }}:{{ db_port }}/{{ item.db_name }}"
  loop: "{{ projects }}"
  loop_control:
    label: "{{ item.name }}"
  become: yes
  become_user: "{{ lookup('env', 'AIDA_USER') }}"

